# Development
services:
   # nginx
   web:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

   # php
   # add volumes: - /var/www/html/vendor for auto-generation ./vendor
   app:
      build:
        dockerfile: ./php/Dockerfile
      volumes:
        - ./app:/var/www/html
      environment:
        MYSQL_HOST: db
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}

   # mysql (https://hub.docker.com/_/mysql/tags)
   # If has not mysql 8.0 use different port e.g: "4306:3306", or by default "3306:3306"
   db:
     image: mysql:8.0
     volumes:
       - mysqldata:/var/lib/mysql
     ports:
       - "4306:3306"
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_USER: user
       MYSQL_PASSWORD: secret
       MYSQL_DATABASE: docker-php

   # redis

# defaults
volumes:
  mysqldata: